# Generated by Django 5.0.3 on 2024-08-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qualifications',
            field=models.CharField(blank=True, choices=[('SSLC', 'SSLC'), ('+2', 'Plus Two'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('PG', 'Postgraduate'), ('PHD', 'PhD')], default='', max_length=255),
        ),
    ]
