# Generated by Django 4.2.5 on 2024-08-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
