# Generated by Django 4.2.5 on 2024-08-28 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_otp_delete_otp'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projectuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='username',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
