# Generated by Django 4.2.5 on 2024-08-29 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_projectuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('hobbies', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.CharField(blank=True, max_length=255, null=True)),
                ('smoking_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('drinking_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('short_reel', models.FileField(blank=True, null=True, upload_to='short_reels/')),
                ('additional_images', models.ManyToManyField(blank=True, to='accounts.additionalimage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
