# Generated by Django 4.2.5 on 2024-08-29 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_additionalimage_personaldetails_delete_projectuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='profile_pictures/')),
                ('hobbies', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('is_registered', models.BooleanField(blank=True, default=False, null=True)),
                ('is_employ', models.BooleanField(blank=True, null=True)),
                ('is_short_term', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
