# Generated by Django 4.2.5 on 2024-08-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_projectuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='additional_images',
            field=models.ManyToManyField(blank=True, to='accounts.additionalimage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='drinking_habits',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hobbies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qualifications',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_reel',
            field=models.FileField(blank=True, default='', null=True, upload_to='short_reels/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='smoking_habits',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
