# Generated by Django 5.0.3 on 2024-09-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_personaldetails_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pics/'),
        ),
    ]
