# Generated by Django 4.2.5 on 2024-08-30 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_projectuser_user_customuser_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalimage',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
