# Generated by Django 5.0.3 on 2024-09-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_friendrequest_profileview_shortlist_story_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profileview',
            name='viewed_user',
        ),
        migrations.RemoveField(
            model_name='profileview',
            name='viewer',
        ),
        migrations.RemoveField(
            model_name='shortlist',
            name='shortlisted_user',
        ),
        migrations.RemoveField(
            model_name='shortlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='ProfileView',
        ),
        migrations.DeleteModel(
            name='Shortlist',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
