# Generated by Django 4.2.5 on 2024-09-03 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_jobprofile_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
