# Generated by Django 5.0.3 on 2024-10-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_friendrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
