# Generated by Django 4.2.15 on 2024-10-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_personaldetails_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='languages_spoken',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
