# Generated by Django 4.2.5 on 2024-09-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_designation_jobprofile_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='jobprofile',
            name='salary',
        ),
        migrations.AddField(
            model_name='jobprofile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
