# Generated by Django 4.2.5 on 2024-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_jobprofile_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
