# Generated by Django 4.2.5 on 2024-09-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_customuser_additional_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='relationship_goals',
            field=models.CharField(blank=True, choices=[('long_term', 'short_term'), ('short_term', 'short_term')], default='', max_length=25, null=True),
        ),
    ]
