# <<<<<<< jeslin
# # Generated by Django 5.1 on 2024-08-30 22:07
# =======
# # Generated by Django 5.0.3 on 2024-09-23 15:24
# >>>>>>> user_account_dating

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
# <<<<<<< jeslin
#             name='Contacted',
#             fields=[
#                 ('id', models.BigAutoField(primary_key=True, serialize=False)),
#                 ('created_at', models.DateTimeField(auto_now_add=True)),
#                 ('contacted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_received', to=settings.AUTH_USER_MODEL)),
#                 ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_made', to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='MatchRequest',
#             fields=[
#                 ('id', models.BigAutoField(primary_key=True, serialize=False)),
#                 ('status', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='sent', max_length=10)),
#                 ('created_at', models.DateTimeField(auto_now_add=True)),
#                 ('updated_at', models.DateTimeField(auto_now=True)),
# =======
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('contacted', 'Contacted')], default='sent', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
# >>>>>>> user_account_dating
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
# <<<<<<< jeslin
#             name='Message',
#             fields=[
#                 ('id', models.BigAutoField(primary_key=True, serialize=False)),
#                 ('content', models.TextField()),
#                 ('timestamp', models.DateTimeField(auto_now_add=True)),
#                 ('is_read', models.BooleanField(default=False)),
#                 ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
#                 ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
#             ],
#         ),
#         migrations.CreateModel(
# =======
# >>>>>>> user_account_dating
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shortlisted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlisted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
# <<<<<<< jeslin
# =======
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dating.story')),
            ],
        ),
# >>>>>>> user_account_dating
    ]
