# Generated by Django 4.2.15 on 2024-09-05 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating', '0002_rename_contacted_user_contacted_contacted_customuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interestin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interestin', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
